// ERRORS
export const EMPTY_ERRORS = 'EMPTY_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';

// ADMIN
export const BEFORE_ADMIN = 'BEFORE_ADMIN';
export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const GET_ADMIN = 'GET_ADMIN';
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

// CATEGORIES
export const BEFORE_CATEGORY = 'BEFORE_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
export const UPSERT_CATEGORY = 'UPSERT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

// INGREDIENTS
export const BEFORE_INGREDIENT = 'BEFORE_INGREDIENT';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENT = 'GET_INGREDIENT';
export const UPSERT_INGREDIENT = 'UPSERT_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';

// FAQs
export const BEFORE_FAQ = 'BEFORE_FAQ';
export const GET_FAQ = 'GET_FAQ';
export const GET_FAQS = 'GET_FAQS';
export const UPSERT_FAQ = 'UPSERT_FAQ';
export const DELETE_FAQ = 'DELETE_FAQ';

// Pizza's
export const BEFORE_PIZZA = 'BEFORE_PIZZA';
export const GET_PIZZAS = 'GET_PIZZAS';
export const SEND_RARITY_REWARD = 'SEND_RARITY_REWARD';

// USERS
export const BEFORE_USER = 'BEFORE_USER';
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const UPSERT_USER = 'UPSERT_USER';
export const DELETE_USER = 'DELETE_USER';

// COLLECTION
export const BEFORE_COLLECTION = 'BEFORE_COLLECTION';
export const GET_COLLECTION = 'GET_COLLECTION';
export const GET_COLLECTIONS = 'GET_COLLECTIONS';
export const UPSERT_COLLECTION = 'UPSERT_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';

// NFT
export const BEFORE_NFT = 'BEFORE_NFT';
export const GET_NFTS = 'GET_NFTS';
export const DELETE_NFT = 'DELETE_NFT';

// Auction
export const BEFORE_AUCTION = 'BEFORE_AUCTION';
export const GET_AUCTION = 'GET_AUCTION';

// Emails
export const GET_EMAILS = 'GET_EMAILS';
export const GET_EMAIL = 'GET_EMAIL';
export const BEFORE_EMAIL = 'BEFORE_EMAIL';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';

// Settings
export const GET_SETTINGS = 'GET_SETTINGS';
export const EDIT_SETTINGS = 'EDIT_SETTINGS';
export const BEFORE_SETTINGS = 'BEFORE_SETTINGS';

// Artists
export const BEFORE_ARTIST = 'BEFORE_ARTIST';
export const GET_ARTIST = 'GET_ARTIST';
export const GET_ARTISTS = 'GET_ARTISTS';
export const UPSERT_ARTIST = 'UPSERT_ARTIST';
export const DELETE_ARTIST = 'DELETE_ARTIST';


// Statistics
export const GET_DASHBOARD_STATS = 'GET_DASHBOARD_STATS';
export const GET_PIZZAS_STATS = 'GET_PIZZAS_STATS';

export const SET_WALLET_ERROR = "SET_WALLET_ERROR";
export const REDIRECT_TO_WALLET = "REDIRECT_TO_WALLET";